<a href="https://colab.research.google.com/github/NamitNaik/Neural-Networks-and-Fuzzy-Logic/blob/master/BPN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

X = np.array(([0, 0], [0, 1], [1, 0],[1, 1]), dtype=float)
t = np.array(([0], [1], [1], [1]), dtype=float)


class Neural_Network():
  def __init__(self):
    #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 2
    #weights
    #np.random.seed(0)
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
   

  def forward(self, X):
    
    self.zin = np.dot(X, self.W1)
    self.z = self.sigmoid(self.zin)
    self.yin = np.dot(self.z, self.W2) 
    y = self.sigmoid(self.yin) 
    return y

  def sigmoid(self, s):  
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    return s * (1 - s)

  def backward(self, X, t, y):
    self.y_error = t - y 
    self.y_delta = self.y_error*self.sigmoidPrime(y)

    self.z_error = self.y_delta.dot(self.W2.T) 
    self.z_delta = self.z_error*self.sigmoidPrime(self.z) 

    self.W1 += X.T.dot(self.z_delta) 
    self.W2 += self.z.T.dot(self.y_delta) 

  

NN = Neural_Network()
for i in range(1000):
  print("iteration:",i)
  print("Input: \n" + str(X))
  print("Actual Output: \n" + str(t))
  y=NN.forward(X)
  print("Predicted Output: \n" + str(y))
  Loss=np.mean(np.square(t - NN.forward(X)))
  print("Loss: \n" + str(Loss))
  if Loss<=0.02:
    break
  print("\n")
  NN.backward(X, t, y)



iteration: 0
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.14599315]
 [0.14769561]
 [0.08652741]
 [0.08812534]]
Loss: 
0.6034210859763504


iteration: 1
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.16496659]
 [0.17718707]
 [0.10809241]
 [0.1168725 ]]
Loss: 
0.5699121064066814


iteration: 2
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.18887215]
 [0.21346713]
 [0.1375255 ]
 [0.15688073]]
Loss: 
0.5272547576982914


iteration: 3
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.21857648]
 [0.25636772]
 [0.17680612]
 [0.20978851]]
Loss: 
0.47571175315006764


iteration: 4
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.254138  ]
 [0.30402756]
 [0.22643102]
 [0.27365916]]
Loss: 
0.418

In [ ]:

import numpy as np

X = np.array(([0, 0], [0, 1], [1, 0],[1, 1]), dtype=float)
t = np.array(([0], [1], [1], [1]), dtype=float)


class Neural_Network():
  def __init__(self):
    #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 2
    #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
   

  def forward(self, X):
    
    self.zin = np.dot(X, self.W1)
    self.z = self.sigmoid(self.zin)
    self.yin = np.dot(self.z, self.W2) 
    y = self.sigmoid(self.yin) 
    return y

  def sigmoid(self, s):  
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    return s * (1 - s)

  def backward(self, X, t, y):
    self.y_error = t - y 
    self.y_delta = self.y_error*self.sigmoidPrime(y)

    self.z_error = self.y_delta.dot(self.W2.T) 
    self.z_delta = self.z_error*self.sigmoidPrime(self.z) 

    self.W1 += X.T.dot(self.z_delta) 
    self.W2 += self.z.T.dot(self.y_delta) 

  

NN = Neural_Network()
for i in range(1000):
  print("iteration:",i)
  print("Input: \n" + str(X))
  print("Actual Output: \n" + str(t))
  y=NN.forward(X)
  print("Predicted Output: \n" + str(y))
  Loss=np.mean(np.square(t - NN.forward(X)))
  print("Loss: \n" + str(Loss))
  if Loss<=0.06:
    break
  print("\n")
  NN.backward(X, t, y)



iteration: 0
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.24576318]
 [0.26682368]
 [0.2185072 ]
 [0.24698366]]
Loss: 
0.4439279176645603


iteration: 1
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.29051544]
 [0.33488878]
 [0.28325853]
 [0.33081739]]
Loss: 
0.37207396106154594


iteration: 2
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.33961156]
 [0.40809495]
 [0.35588706]
 [0.42156519]]
Loss: 
0.3037889754776625


iteration: 3
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.38741184]
 [0.47752376]
 [0.42699027]
 [0.50627496]]
Loss: 
0.24879347919884892


iteration: 4
Input: 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.4291489 ]
 [0.5368722 ]
 [0.48908238]
 [0.57679963]]
Loss: 
0.20